# Generated by Django 5.2.8 on 2026-09-05 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_file_hash_video_file_size_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='authenticity_score',
            field=models.IntegerField(default=100, help_text='Authenticity Confidence Score (0-100%)'),
        ),
        migrations.AddField(
            model_name='video',
            name='container_format',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='md5_hash',
            field=models.CharField(blank=True, help_text='MD5 Checksum', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='verification_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='file_hash',
            field=models.CharField(blank=True, help_text='SHA-256 Checksum', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL),
        ),
    ]
